### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by mxmartins**
Update Unbound from version 1.10.1 to version 1.11.0....
First time doing this on GitHub, hope I did not mess it up...

### CODE REVIEW

**Comment by MatthewVance** [comment]
Thanks for the PR. You did it right. Once I test and merge, I also update the supported tags section of the README.

**Comment by MatthewVance** [comment]
Looking at this more closely, this wasn't done quite right. The code itself looks okay and the PR came through. However, for updates a new folder and Dockerfile needs to be created (versus updating an existing one). 

I normally copy the prior version's folder to a new folder that has the new version name, make any necessary updates like you did in this Dockerfile, and then update the README.

Let me know if you want to re-submit an update pull request or would rather me close this and make the changes on my end. If I don't hear back in a day or so, I'll go ahead and make the update so everyone can have the latest release.

Thanks again.

**Comment by mxmartins** [comment]
Ok, since I’m trying to learn this process, let me give it a try….  If I can’t “get there”, I’ll let you know.  I’m hoping to get this figured out tonight…

**Comment by mxmartins** [comment]
Closed pulled request since some information is missing...  New pull request to be submitted later.

**Comment by MatthewVance** [comment]
Sounds good.

**Comment by mxmartins** [comment]
Just submitted the “correct” pull request..  Thanks

**Pull request closed without merging**
