### PR TITLE
README: Add k3s section

### LINKED ISSUE #84: Unbound on k3s/k8s
Sadly https://github.com/MatthewVance/unbound-docker/issues/60 was never finished but anyway I moved past this now.

The remaining problem is the following: I do have a custom configuration mounted as a projected volume. This means the directory `/opt/unbound/etc/unbound` becomes read-only since this is required to my understanding of projected volumes in Kubernetes.

The workaround for this which I suggest is simple: Let's create a location in the image - `/config` for example - and if there are configfiles, they get copied to the "final" location `/opt/unbound/etc/unbound`. This would be transparent as the startup script would do this on every container restart and thus an updated configuration file would be reflected on a container restart.

### PR DESCRIPTION
**Pull request by SchoolGuy**
This fixes #84 

This is a first draft for adding k3s deployment instructions. In the long run I would propose a separate repo which should evolve into a helmchart. The different environments we have in k8s environments require a lot of documentation not required for Docker.

Since this is a first draft, I am open for changes in any way desired.

### CODE REVIEW

**Comment by MatthewVance** [comment]
Thanks for drafting this. It looks good overall. It's longer than most of the existing README sections. What do you think about making this a second help page and linking to it from a new, short section in the README?

**Comment by SchoolGuy** [comment]
@MatthewVance Sure thing I can do that. I will work with commits and squash them once you are happy. Sorry for the long wait, I was/am out sick.

**Comment by MatthewVance** [comment]
No worries and no rush. I appreciate the update. Get better soon.

**Comment by SchoolGuy** [comment]
@MatthewVance A few thoughts:

- In theory one could build a Helmchart and via the templating you could automate the generation of the files. (I don't have the time atm)
- Also this could be the start of the operator pattern. However this is a lot of work but with a lot of CRDs and some Go code you could make this first-class k8s. (Still time...)
- My implementation via Secrets is... one way to do it. Other people might want to do it via a real volume with files or projected volumes.

> A fair warning: I am using not using a Service but `hostPort`, thus this is only a start. In theory one should not do that in a production cluster.

This is (with the exception of my A-records) exactly what I use in my k3s cluster in my homelab.

**Comment by MatthewVance** [comment]
There's a lot of ways to go about this like you mention above. I don't want to be in the business of providing first class K8S support so  I think the current PR is sufficient to get people going with a working Kubernetes example.  It may be worth adding your warning note about using hostPort to the Readme so folks can decide if that's something they want to change before using the example as is. Something like a Service is preferable. 

Using Secrets is reasonable as a basic example as that's built-in to newer versions of K8S. Of course for a real prod deployment, a more secure secrets engine should be used because "Kubernetes Secrets are, by default, stored unencrypted in the API server's underlying data store (etcd)" per https://kubernetes.io/docs/concepts/configuration/secret/. If you want, you could also add a pointer to the Kubernetes documentation which explains how the default Secrets engine can be made more secure (i.e., [Enable Encryption at Rest for Secrets](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/), [use RBAC](https://kubernetes.io/docs/reference/access-authn-authz/authorization/) to restrict reading data in Secrets [including indirect means such as this example [escalation path](https://kubernetes.io/docs/reference/access-authn-authz/authorization/#privilege-escalation-via-pod-creation)], and limit which principals are allowed to create or replace Secrets).

Personally, I'd consider using HashiCorp Vault to manage the secrets, but that's not a good default example to provide. 

If you can add those notes and squash the commits, this should be ready to merge. Thanks again!

**Comment by SchoolGuy** [comment]
@MatthewVance Perfect. Will do today after work!

**Comment by SchoolGuy** [comment]
Okay so this was not today but I finally took time for this PR. I am deeply sorry that I wasn't able to schedule it earlier. I hope all is fine now!

**Comment by MatthewVance** [comment]
No worries. Thanks for the contribution.

**Pull request merged**
