### PR TITLE
Allow setting healthcheck domain with an environment variable

### PR DESCRIPTION
**Pull request by tnyeanderson**
It should be easy to set the domain for the HEALTHCHECK without having to copy/repeat/redefine the entire health check command.

This PR:
- Adds an environment variable `HEALTHCHECK_DOMAIN` to the container with default value `cloudflare.com`
- Replaces `cloudflare.com` in the health check command with `"${HEALTHCHECK_DOMAIN}"`

Therefore allowing the user to set which domain is queried for the health check.

Due to the directory structure, a diff is provided below for clarity:
```
diff -urN 1.16.2/Dockerfile 1.16.3/Dockerfile
--- 1.16.2/Dockerfile   2022-09-07 22:31:39.284900810 -0400
+++ 1.16.3/Dockerfile   2022-09-07 22:38:06.670352779 -0400
@@ -102,6 +102,8 @@
     SUMMARY="${NAME} is a validating, recursive, and caching DNS resolver." \
     DESCRIPTION="${NAME} is a validating, recursive, and caching DNS resolver."

+ENV HEALTHCHECK_DOMAIN=cloudflare.com
+
 WORKDIR /tmp/src

 COPY --from=unbound /opt /opt
@@ -144,6 +146,6 @@
 EXPOSE 53/tcp
 EXPOSE 53/udp

-HEALTHCHECK --interval=30s --timeout=30s --start-period=10s --retries=3 CMD drill @127.0.0.1 cloudflare.com || exit 1
+HEALTHCHECK --interval=30s --timeout=30s --start-period=10s --retries=3 CMD drill @127.0.0.1 "${HEALTHCHECK_DOMAIN}" || exit 1

 CMD ["/unbound.sh"]
```

Retrieved with:
```bash
diff -urN 1.16.{2,3}
```

### CODE REVIEW

**Comment by tnyeanderson** [comment]
Unfortunately I'm no longer using this project, and due to its repo structure I can't maintain this PR with upstream conflict resolution, etc. The basic idea outlined in my PR should still work and be easy to implement. Best of luck and thanks for the hard work on this!

**Comment by Simpuhl** [comment]
This is still much needed in Unbound

**Comment by tnyeanderson** [comment]
Feel free to open an issue/PR, the implementation is extremely straightforward. The problem is that the structure of this repo makes review and conflict resolution extremely difficult. And since I no longer use the project, I don't feel any desire to continue hacking on it :)

**Comment by Simpuhl** [comment]
> Feel free to open an issue/PR, the implementation is extremely straightforward. The problem is that the structure of this repo makes review and conflict resolution extremely difficult. And since I no longer use the project, I don't feel any desire to continue hacking on it :)

I am a simple PowerShell guy, I never got much into anything else or I would. Curious what you use now if anything that replaced Unbound?

**Comment by tnyeanderson** [comment]
Adguardhome is what I use now. Hopefully someone can come along and take this one to the hoop otherwise :)

**Pull request closed without merging**
