### PR TITLE
Update Unbound to 1.13.0

### PR DESCRIPTION
**Pull request by mxmartins**

### CODE REVIEW

**Comment by beroliv** [comment]
ibuild build 1.13 at my Server  but dont work. also klutchell/unbound dont work it has the same error.
and Pihole can't connect on unbound. Reinstall Matthews Version and all are running fine.
[1607543446] libunbound[47:0] error: udp connect failed: Address not available for 2001:500:200::b port 53
[1607543446] libunbound[47:0] error: udp connect failed: Address not available for 2001:7fe::53 port 53
[1607543446] libunbound[47:0] error: udp connect failed: Address not available for 2001:500:a8::e port 53

**Review by MatthewVance — APPROVED** [review]
Looks good

**Comment by MatthewVance** [comment]
@beroliv your error message implies you're trying to use IPv6. Docker must be configured to support IPv6. All current instances of my Unbound image are setup to only run with IPv4.

**Comment by melchormx** [comment]
imagen

Google translate:
I was a little late to the discussion, but in fact I also replicated the steps and found the same error, which now is reflected in the main branch as well. I want to assume that it is due to what was said above.

**Comment by MatthewVance** [comment]
I'm seeing the error as well now and opened issue https://github.com/MatthewVance/unbound-docker/issues/55 for this and am not yet sure why. I didn't see anything in the Unbound change log for 1.13.0 related to IPv6. However, it must be something new to this release because the configuration settings are the same as before. Perhaps IPv6 now has to be explicitly denied?

**Comment by dmgm** [comment]
I just tried this with the latest image on a dual stack network.
I am getting some errors
[1618442130] libunbound[19:0] error: udp connect failed: Cannot assign requested address for 2001:500:2d::d port 53,
[1618442130] libunbound[19:0] error: udp connect failed: Cannot assign requested address for 2001:500:200::b port 53

But the server says it's healthy (under portainer) and it appears to work.

➜  ~ nslookup -port=53 pornhub.com 192.168.3.10
Server:         192.168.3.10
Address:        192.168.3.10#53

Non-authoritative answer:
Name:   pornhub.com
Address: 66.254.114.41

Nice to have the ability to run this so easily. Thanks

**Pull request merged**
