### PR TITLE
Update to 1.12.0

### PR DESCRIPTION
**Pull request by mxmartins**
Update DNS Unbound to version 1.12.0

### CODE REVIEW

**Comment by jcbvm** [comment]
They changed the default edns-buffer-size in this release to 1232:
"Default  is  1232 which is the DNS Flag Day 2020 recommendation."

Should the config be changed to reflect this change?

**Comment by mxmartins** [comment]
I looked at it, and felt that a changed is not necessary…  Most use a MTU of 1500, and don’t see why most of us need to adapt to an edns-buffer-size of 1232…

**Comment by MatthewVance** [comment]
Thanks for the work on this.

As for the buffer size, I think we should leave it as is for now. I'm open
to suggestions, but think it should be in its own issue rather than
included as part of a version update PR.

This may provide good background:
https://github.com/dns-violations/dnsflagday/issues/125

**Comment by mxmartins** [comment]
I’m still not seeing it on the Docker Registry and available for download…  I don’t see an entry for 1.12.0….  Only Latest and 1.11.0….

**Comment by MatthewVance** [comment]
My apologies. I had a number of unexpected events occur that delayed me getting this built and pushed. Try now.

**Comment by mxmartins** [comment]
Yes, it’s there now…  Thank you…

**Comment by mxmartins** [comment]
I installed it on one of my Docker containers and all is well…  

 

In another machine, the Docker container, with the same exact unbound.conf settings, I am getting this error…  Any idea why?

 

/opt/unbound/sbin/unbound-anchor: error while loading shared libraries: libnghttp2.so.14: cannot open shared object file: No such file or directory

/opt/unbound/sbin/unbound: error while loading shared libraries: libnghttp2.so.14: cannot open shared object file: No such file or directory

**Comment by MatthewVance** [comment]
There's a bug in the latest. I missed something when adding the DoH
package. The 1.12.0 tagged one should still work.

**Pull request merged**
